# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8673190cc4d85b086b05637f7cc0380fe974c728cdc10c4776e0bc0b2dae4f4ee096038bba37bc685cd9f260e9feaa23f8951e09e14e8cd26ddc6e9865217d12

test:
  secret_key_base: eb509633c3cdc725a4be4731de4a3442ea37deac17fc70b440604647931a305d4f23b35302f59f43ce6a1184b3e6f7d8129adfecf3801a469d173234a0d38d49

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
